### ISSUE TITLE
Armar paso a paso para configurar entorno virtual

### ISSUE THREAD

**Issue by cacrespo** [cacrespo/django_tyv#10]
Creo que sería bueno que tengamos un pequeño paso a paso sobre cómo configurar el entorno virtual.
Ya sé que hay miles de tutoriales! 😉 

Pero creo que estaría bueno como ejercicio para nosotros y además lo dejamos como parte de la documentación a la hora de probar el sitio o realizar mejoras.
¿qué dicen?

pyenv
virtualenv
poetry
¿?

**Comment by gianfranco-s** [comment]
Estoy de acuerdo con lo de los tutoriales.
En este caso, agregué el paso a paso en `README.md`
Luego fue movido a `faq.md`
