### ISSUE TITLE
añadir código de conducta

### ISSUE THREAD

**Issue by cacrespo** [cacrespo/django_tyv#11]

**Comment by jsanchez23** [comment]
hola

**Comment by cacrespo** [comment]
@jsanchez23 Te lo asigno. Cualquier duda que tengas  la vemos en el chat. 💪

**Comment by cothey** [comment]
Quienes formamos parte de este proyecto nos comprometemos a mantener un ambiente confortable y seguro para todas las personas, más allá de su identidad y expresión de género, orientación sexual, discapacidades, apariencia física, etnia, nacionalidad, religión (o falta de la misma), nivel socioeconómico u otras características personales.

**Comment by cothey** [comment]
es una prueba...sirve?

**Comment by cacrespo** [comment]
> Quienes formamos parte de este proyecto nos comprometemos a mantener un ambiente confortable y seguro para todas las personas, más allá de su identidad y expresión de género, orientación sexual, discapacidades, apariencia física, etnia, nacionalidad, religión (o falta de la misma), nivel socioeconómico u otras características personales.

Muy bueno @cothey. Fijate que ya lo estamos discutiendo en #13 . ¿Te parece si lo integras directamente en el PR?
