### ISSUE TITLE
Modelado Base de Datos

### ISSUE THREAD

**Issue by jorgeopichani** [cacrespo/django_tyv#19]
- ID
- Código de Producto (puede ser interno o código de barra)
- Marca
- Fecha de ingreso
- Talles
- Cantidad x Paquete
- Cantidad x Bulto
- Fecha de egreso
- Precio de ingreso
- Precio de venta
- Cantidad vendida
- Stock
- Proveedor
    - Teléfono del proveedor
   - Correo-e Proveedor
    - Dirección del Proveedor
- Cliente
    -  Teléfono
    - dirección
    - medios de pago
    - Producto
        - Cantidad
        - Talle

**Comment by cacrespo** [comment]
Genial @jorgeopichani !

No termino de entender. ¿Cuántas tablas te imaginas que necesitamos? ¿y cuál sería la relación entre cada tabla?

Supongo que estas si o sí deberían estar:
clientes,
ventas,
proveedores,
productos

**Comment by jorgeopichani** [comment]
Lo arme en mi cabeza como una gran tabla de excel, jejeje pero si esas cuatro son las bases y me gustaría agregar una para el cierre de caja y esas cosas pero no se nunca hice una mas allá de un excel

**Comment by cacrespo** [comment]
OK @jorgeopichani te asigno el issue. Si te parece mejor podemos discutirlo en el chat y una vez que lleguemos a un acuerdo volcamos acá el resultado para que quede constancia.

**Comment by jorgeopichani** [comment]
Perfecto
