### ISSUE TITLE
“productos principales” + “productos secundarios”

### ISSUE THREAD

**Issue by cacrespo** [cacrespo/django_tyv#3]

**Comment by guillermo-k** [comment]
Los productos deberían contar con 2 campos que el propietario pueda marcar, y así seleccionarlos como destacado principal, y destacado secundario.
los destacados principal irán mas grandes en el centro de la pagina, y los destacados secundarios, en forma de lista debajo.

**Comment by cacrespo** [comment]
closes by #6849c43
